### ISSUE TITLE
完整汉化

### ISSUE THREAD

**Issue by warycodehub** [KuroNoSeiHai/Translation.ini#1]
大佬能不能把快捷键说明部分的汉化也加上

**Comment by KuroNoSeiHai** [comment]
快捷键如果源码没写上的话不行，我回头看看，如果有的话我会补充上。否则就算我添加了，源码里没有也没有作用

**Comment by KuroNoSeiHai** [comment]
> 大佬能不能把快捷键说明部分的汉化也加上

快捷键如果源码没写上的话不行，我回头看看，如果有的话我会补充上。否则就算我添加了，源码里没有也没有作用

**Comment by warycodehub** [comment]
这样啊，感觉像是一个控件的一部分，可能源码上就没有，谢谢你的热情回复和辛勤付出发自我的华为手机

**Comment by KuroNoSeiHai** [comment]
> 这样啊，感觉像是一个控件的一部分，可能源码上就没有，谢谢你的热情回复和辛勤付出发自我的华为手机

您说的是哪个快捷键，如果是游戏内的快捷键汉化的话是在HotKeySetting.ini里，不在这个文件汉化

**Comment by warycodehub** [comment]
我说的就是HotKeySetting文件里面的，不能放在translation吗

**Comment by KuroNoSeiHai** [comment]
> 我说的就是HotKeySetting文件里面的，不能放在translation吗

那个汉化HotKeySetting.ini，这个Translation.ini是负责客户端UI的。不过我可以把汉化好的HotKeySetting也发出来。

**Comment by warycodehub** [comment]
谢谢你
